apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: session-db
  namespace: argocd
spec:
  destination:
    namespace: eshop-staging
    server: https://kubernetes.default.svc
  project: eshop-staging
  source:
    helm:
      valueFiles:
        - values.yaml
    path: services/session-db
    repoURL: https://github.com/tuskacten/ptuddn-2025.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
