---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
    {{- if eq .Values.spec.type "LoadBalancer" }}
    nodePort: 30001
    {{- end }}
  selector:
    name: front-end
