apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-cluster-bootstrap
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: k8s-config
  source:
    helm:
      valueFiles:
        - values.yaml
    path: k8s/k8s-cluster-bootstrap
    repoURL: https://github.com/tuskacten/ptuddn-2025.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

